### ISSUE TITLE
Replace automated Faraday logging

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/sapi-client-ruby#48]
I noticed while looking at https://github.com/epimorphics/regulated-products/issues/519 that we're still relying on Faraday to log calls to the remote API (see `instance.rb`, line 58).

Following recent conversations with @andrew-pickin-epi, I've moved away from Faraday's built-in logger, and instead make an explicit call to the logger to record the interaction. 

Specifically, ops would like to see one line in the log that records, in one single JSON log entry:

- the API URL that was invoked
- the response code from the API
- the duration of the call

There's an example of this change in the [`data_services_api`](https://github.com/epimorphics/data_services_api/blob/434167dff3b6a33bda7b1becffac5926b6d05de6/lib/data_services_api/service.rb#L172), for reference.

**Comment by jonrandahl** [comment]
@tomguilbert I believe this ticket will be resolved with the [updates to the data services api gem](https://github.com/epimorphics/data_services_api/pull/10) however these changes will also need to be tested on the [regulated products dev server](https://fsa-rp-test.epimorphics.net/regulated-products) to confirm.

**Comment by tomguilbert** [comment]
@jonrandahl should this be part of the app enhancements backlog? If so I can't add the 'app' label

**Comment by jonrandahl** [comment]
This can be closed as was previously marked as resolved in multiple locations:

- https://github.com/epimorphics/regulated-products/issues/497#issuecomment-1111196827
- https://github.com/epimorphics/regulated-products/issues/519
- https://github.com/epimorphics/regulated-products-app/pull/384

and subsequently linked tickets and PR's from above.
