### ISSUE TITLE
Release mechanism broke

### ISSUE THREAD

**Issue by ajtucker** [epimorphics/sapi-client-ruby#59]
See https://github.com/epimorphics/sapi-client-ruby/actions/runs/11232469507/job/31224124104

Do we need
```Makefile
.PHONY: ${PAT}
```
?

**Comment by andrew-pickin-epi** [comment]
No. The ${PAT} dependancy is wrong, looking at the lr common styles.

**Comment by andrew-pickin-epi** [comment]
https://github.com/epimorphics/sapi-client-ruby/commit/e8ab8345679b6bca537843d11c06eaf841718479

**Comment by ajtucker** [comment]
Thanks @andrew-pickin-epi, that fixed it.
